from tkinter import *

agn = Tk()
Label(agn, text='First Name').grid(row=0)
Label(agn, text='Last Name').grid(row=1)
Label(agn, text='Phone Number').grid(row=2)
Label(agn, text='adress').grid(row=3)
Label(agn, text='email').grid(row=4)
e1 = Entry(agn)
e2 = Entry(agn)
e3 = Entry(agn)
e4 = Entry(agn)
e5 = Entry(agn)
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
e4.grid(row=3, column=1)
e5.grid(row=4, column=1)
agn.mainloop()